version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "8080:443"
    links:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - mysql
      - redis
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
  php-cli:
    build:
      context: .
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - mysql
      - redis
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
    tty: true
  mysql:
    image: mysql:5.7
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=123"
      - "MYSQL_USER=advert"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=advert"
    ports:
      - "33061:3306"
  redis:
    image: redis:3.0
    ports:
      - "63791:6379"
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - 8099:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: advert
      MYSQL_PASSWORD: secret
  node:
    image: node:8.6-alpine
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
